---
- name: Create Cassandra data volumes
  containers.podman.podman_volume:
    state: present
    name: 'cortex-cassandra-{{ item }}-volume'
    label:
      app: cortex
  loop: '{{ range(0, cortex_cassandra_replicas)|list }}'

- name: Create Cassandra pods
  containers.podman.podman_pod:
    name: 'cortex-cassandra-{{ item }}-pod'
    state: started
    network: '{{ cortex_backend_podman_network }}'
    hostname: 'cortex-cassandra-{{ item|string + "." + cortex_domain }}'
  loop: '{{ range(0, cortex_cassandra_replicas)|list }}'

- name: Get infra pods
  containers.podman.podman_pod_info:
    name: 'cortex-cassandra-{{ item|string }}-pod'
  register: pod_info
  loop: '{{ range(0, cortex_cassandra_replicas)|list }}'

- set_fact:
    cortex_cassandra_ids: '{{ cortex_cassandra_ids|default([]) + [ pod_info.results[ item ].pods[0].InfraContainerID ] }}'
  loop: '{{ range(0, cortex_cassandra_replicas)|list }}'

- name: get pod IP
  containers.podman.podman_container_info:
    name: '{{ item }}'
  register: container_info
  loop: '{{ cortex_cassandra_ids }}'

- set_fact:
    cortex_cassandra_pod_ips: '{{ container_info | json_query(query) }}'
  vars:
    query: 'results[*].containers[0].NetworkSettings.Networks.{{ cortex_backend_podman_network }}.IPAddress'

- name: Setup Cassandra Cluster
  containers.podman.podman_container:
    name: 'cortex-cassandra-{{ item }}'
    image: 'docker.io/library/cassandra:{{ cortex_cassandra_version }}'
    pod: 'cortex-cassandra-{{ item }}-pod'
    conmon_pidfile: '{{ cortex_base_dir }}/pids/cassandra{{ item }}.pid'
    volume:
      - 'cortex-cassandra-{{ item }}-volume:/var/lib/cassandra:Z'
    env:
      CASSANDRA_SEEDS: "{{ cortex_cassandra_pod_ips | join(',') }}"
      CASSANDRA_CLUSTER_NAME: "cortex-bos2"
      CASSANDRA_DC: "bos2"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    state: started
  register: cassandra
  loop: '{{ range(0, cortex_cassandra_replicas)|list }}'

- pause:
    prompt: "Waiting for Cassandra to start up..."
    minutes: 1
  when: cassandra.changed

- name: Create Cortex keyspace
  shell: podman exec cortex-cassandra-0 cqlsh -e "{{ query }}"
  changed_when: false
  vars:
    query: "CREATE KEYSPACE if NOT EXISTS {{ cortex_cassandra_keyspace }} WITH replication = {'class':'SimpleStrategy', 'replication_factor' : {{ cortex_cassandra_replication_factor }} };"

- set_fact:
    cortex_cassandra_containers: '{{ cortex_cassandra_containers|default([]) + [ "cortex-cassandra-" +  item|string ] }}'
  loop: '{{ range(0, cortex_cassandra_replicas)|list }}'

- name: Generate systemd files for cassandra cluster
  include_tasks: systemd.yml
  loop: '{{ cortex_cassandra_containers }}'
