---
- name: Create Distributor pods
  containers.podman.podman_pod:
    name: 'cortex-distributor-{{ item }}-pod'
    state: started
    network: '{{ cortex_backend_podman_network }}'
    hostname: 'cortex-distributor-{{ item|string + "." + cortex_domain }}'
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- name: Get Distributor Infra Containers
  containers.podman.podman_pod_info:
    name: 'cortex-distributor-{{ item|string }}-pod'
  register: pod_info
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- set_fact:
    cortex_distributor_ids: '{{ cortex_distributor_ids|default([]) + [ pod_info.results[ item ].pods[0].InfraContainerID ] }}'
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- name: get pod IP
  containers.podman.podman_container_info:
    name: '{{ item }}'
  register: container_info
  loop: '{{ cortex_distributor_ids }}'

- set_fact:
    cortex_distributor_pod_ips: '{{ container_info | json_query(query) }}'
  vars:
    query: 'results[*].containers[0].NetworkSettings.Networks.{{ cortex_backend_podman_network }}.IPAddress'

- name: Setup Cortex Distributors
  containers.podman.podman_container:
    name: 'cortex-distributor-{{ item }}'
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    pod: 'cortex-distributor-{{ item }}-pod'
    conmon_pidfile: '{{ cortex_base_dir }}/pids/cortex-distributor-{{ item }}.pid'
    volume:
      - '{{ cortex_base_dir }}/cortex-config/cortex.yaml:/etc/cortex.yaml:z'
    command: '-target=distributor -config.file=/etc/cortex.yaml'
    state: started
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- set_fact:
    cortex_distributor_containers: '{{ cortex_distributor_containers|default([]) + [ "cortex-distributor-" +  item|string ] }}'
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- name: Generate systemd files for distributors
  include_tasks: systemd.yml
  loop: '{{ cortex_distributor_containers }}'

- name: Restart Service(s)
  systemd:
    name: 'container-cortex-distributor-{{ item }}.service'
    state: restarted
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'
  when: cortex_conf.changed

# Cleanup/scale down
- name: Get list of all distributor pods
  shell: /usr/bin/podman pod ps | grep -o -e 'cortex-distributor-[0-9]\+-pod'
  register: distributor_pods
  changed_when: false

- set_fact:
    pods_in_use: "{{ pods_in_use|default([]) + [ 'cortex-distributor-' + item|string + '-pod' ] }}"
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- set_fact:
    pods_to_cleanup: '{{ distributor_pods.stdout_lines }}'

- set_fact:
    pods_to_cleanup: "{{ pods_to_cleanup | difference(pods_in_use) }}"
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- debug:
    msg: 'Distributor pods to clean up: {{ pods_to_cleanup }}'

- name: Cleanup unused Distributor pods
  containers.podman.podman_pod:
    name: '{{ item }}'
    state: absent
  loop: '{{ pods_to_cleanup }}'

- name: Cleanup unused Distributor service files
  file:
    path: "/etc/systemd/system/container-{{ item | regex_replace('-pod') }}.service"
    state: absent
  loop: '{{ pods_to_cleanup }}'
  notify: daemon-reload
