---
- name: Create Cortex config directory
  file:
    path: /var/lib/containers/cortex-config/
    mode: '0775'
    state: directory

- name: Create Ingester WAL directories
  file:
    path: '/var/lib/containers/cortex-ingester-wal-{{ item }}'
    mode: '0775'
    state: directory
  when: cortex_ingesters_with_wal|bool == True
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: Set Cortex conf file
  template:
    src: 'cortex.yaml'
    dest: '/var/lib/containers/cortex-config/cortex.yaml'
    mode: '0644'

- name: Create Distributor pods
  containers.podman.podman_pod:
    name: 'cortex-distributor-{{ item }}-pod'
    state: started
    network: '{{ cortex_podman_network }}'
    hostname: 'cortex-distributor-{{ item|string + "." + cortex_domain }}'
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- name: Get Distributor Infra Containers
  containers.podman.podman_pod_info:
    name: 'cortex-distributor-{{ item|string }}-pod'
  register: pod_info
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'
  when: cortex_single_host_deployment == true

- set_fact:
    cortex_distributor_ids: '{{ cortex_distributor_ids|default([]) + [ pod_info.results[ item ].pods[0].State.infraContainerID ] }}'
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- name: get pod IP
  containers.podman.podman_container_info:
    name: '{{ item }}'
  register: container_info
  loop: '{{ cortex_distributor_ids }}'

- set_fact:
    cortex_distributor_pod_ips: '{{ container_info | json_query(query) }}'
  vars:
    query: 'results[*].containers[0].NetworkSettings.Networks.{{ cortex_podman_network }}.IPAddress'

- name: Setup Cortex Distributors
  containers.podman.podman_container:
    name: 'cortex-distributor-{{ item }}'
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    pod: 'cortex-distributor-{{ item }}-pod'
    conmon_pidfile: '/var/lib/containers/pids/cortex-distributor-{{ item }}.pid'
    volume:
      - '/var/lib/containers/cortex-config/cortex.yaml:/etc/cortex.yaml:Z'
    command: '-target=distributor -config.file=/etc/cortex.yaml'
    state: started
#    restart_policy: always
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- name: Create Ingesters pods
  containers.podman.podman_pod:
    name: 'cortex-ingester-{{ item }}-pod'
    state: started
    network: '{{ cortex_podman_network }}'
    hostname: 'cortex-ingester-{{ item|string + "." + cortex_domain }}'
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: Setup Cortex Ingesters without WAL
  containers.podman.podman_container:
    name: 'cortex-ingester-{{ item }}'
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    pod: 'cortex-ingester-{{ item }}-pod'
    conmon_pidfile: '/var/lib/containers/pids/cortex-ingester-{{ item }}.pid'
    volume:
      - '/var/lib/containers/cortex-config/cortex.yaml:/etc/cortex.yaml:Z'
    command: '-target=ingester -config.file=/etc/cortex.yaml'
    state: started
#    restart_policy: always
  when: cortex_ingesters_with_wal|bool == False
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: Setup Cortex Ingesters with WAL
  containers.podman.podman_container:
    name: 'cortex-ingester-{{ item }}'
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    pod: 'cortex-ingester-{{ item }}-pod'
    conmon_pidfile: '/var/lib/containers/pids/cortex-ingester-{{ item }}.pid'
    volume:
      - '/var/lib/containers/cortex-config/cortex.yaml:/etc/cortex.yaml:Z'
      - '/var/lib/containers/cortex-ingester-wal-{{ item }}:/wal:Z'
    command: '-target=ingester -config.file=/etc/cortex.yaml'
    state: started
#    restart_policy: always
  when: cortex_ingesters_with_wal|bool == True
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

#- name: Generate systemd files for Cortex cluster
#  include_tasks: systemd.yml
