---
- name: Setup Cortex Query Frontend
  containers.podman.podman_container:
    name: cortex-query-frontend
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    network: '{{ cortex_backend_podman_network }}'
    conmon_pidfile: '{{ cortex_base_dir }}/pids/cortex-query-frontend.pid'
    volume:
      - '{{ cortex_base_dir }}/cortex-config/cortex.yaml:/etc/cortex.yaml:z'
    command: '-target=query-frontend -config.file=/etc/cortex.yaml'
    state: started

- name: Generate systemd files for Query Frontend
  include_tasks: systemd.yml
  loop:
    - cortex-query-frontend

- name: Get Container info
  containers.podman.podman_container_info:
    name: cortex-query-frontend
  register: container_info
- set_fact:
    cortex_query_frontend_ip: '{{ container_info | json_query(query) }}'
  vars:
    query: 'containers[0].NetworkSettings.Networks.{{ cortex_backend_podman_network }}.IPAddress'
