---
- name: Create Query Frontend Pod
  containers.podman.podman_pod:
    name: cortex-query-frontend-pod
    state: started
    network: '{{ cortex_backend_podman_network }}'
    hostname: 'cortex-query-frontend.{{ cortex_domain }}'

- name: Setup Cortex Query Frontend
  containers.podman.podman_container:
    name: cortex-query-frontend
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    conmon_pidfile: '{{ cortex_base_dir }}/pids/cortex-query-frontend.pid'
    pod: cortex-query-frontend-pod
    volume:
      - '{{ cortex_base_dir }}/cortex-config/cortex.yaml:/etc/cortex.yaml:z'
    command: '-target=query-frontend -config.file=/etc/cortex.yaml'
    state: started

- name: Generate systemd files for Query Frontend
  include_tasks: systemd.yml
  loop:
    - cortex-query-frontend

- name: Restart Service(s)
  systemd:
    name: container-cortex-query-frontend.service
    state: restarted
  when: cortex_conf.changed

- name: Get Query Frontend pod infra container
  containers.podman.podman_pod_info:
    name:  cortex-query-frontend-pod
  register: pod_info

- set_fact:
    cortex_query_frontend_id: '{{ pod_info.pods[0].InfraContainerID }}'

- name: Get Query Frontend Pod IP
  containers.podman.podman_container_info:
    name: '{{ cortex_query_frontend_id }}'
  register: container_info

- set_fact:
    cortex_query_frontend_pod_ip: '{{ container_info | json_query(query) }}'
  vars:
    query: 'containers[0].NetworkSettings.Networks.{{ cortex_backend_podman_network }}.IPAddress'
