---
- name: Create Ingesters pods
  containers.podman.podman_pod:
    name: 'cortex-ingester-{{ item }}-pod'
    state: started
    network: '{{ cortex_backend_podman_network }}'
    hostname: 'cortex-ingester-{{ item|string + "." + cortex_domain }}'
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: Get Ingester Infra Containers
  containers.podman.podman_pod_info:
    name: 'cortex-ingester-{{ item|string }}-pod'
  register: pod_info
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'
  when: cortex_single_host_deployment == true

- set_fact:
    cortex_ingester_ids: '{{ cortex_ingester_ids|default([]) + [ pod_info.results[ item ].pods[0].State.infraContainerID ] }}'
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: get pod IP
  containers.podman.podman_container_info:
    name: '{{ item }}'
  register: container_info
  loop: '{{ cortex_ingester_ids }}'

- set_fact:
    cortex_ingester_pod_ips: '{{ container_info | json_query(query) }}'
  vars:
    query: 'results[*].containers[0].NetworkSettings.Networks.{{ cortex_backend_podman_network }}.IPAddress'

- name: Setup Cortex Ingesters without WAL
  containers.podman.podman_container:
    name: 'cortex-ingester-{{ item }}'
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    pod: 'cortex-ingester-{{ item }}-pod'
    conmon_pidfile: '/var/lib/containers/pids/cortex-ingester-{{ item }}.pid'
    volume:
      - '/var/lib/containers/cortex-config/cortex.yaml:/etc/cortex.yaml:Z'
    command: '-target=ingester -config.file=/etc/cortex.yaml'
    state: started
  when: cortex_ingesters_with_wal|bool == False
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: Setup Cortex Ingesters with WAL
  containers.podman.podman_container:
    name: 'cortex-ingester-{{ item }}'
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    pod: 'cortex-ingester-{{ item }}-pod'
    conmon_pidfile: '/var/lib/containers/pids/cortex-ingester-{{ item }}.pid'
    volume:
      - '/var/lib/containers/cortex-config/cortex.yaml:/etc/cortex.yaml:Z'
      - '/var/lib/containers/cortex-ingester-wal-{{ item }}:/wal:Z'
    command: '-target=ingester -config.file=/etc/cortex.yaml'
    state: started
  when: cortex_ingesters_with_wal|bool == True
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'
