---
- name: Create Distributor pods
  containers.podman.podman_pod:
    name: 'cortex-distributor-{{ item }}-pod'
    state: started
    network: '{{ cortex_backend_podman_network }}'
    hostname: 'cortex-distributor-{{ item|string + "." + cortex_domain }}'
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- name: Get Distributor Infra Containers
  containers.podman.podman_pod_info:
    name: 'cortex-distributor-{{ item|string }}-pod'
  register: pod_info
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'
  when: cortex_single_host_deployment == true

- set_fact:
    cortex_distributor_ids: '{{ cortex_distributor_ids|default([]) + [ pod_info.results[ item ].pods[0].State.infraContainerID ] }}'
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'

- name: get pod IP
  containers.podman.podman_container_info:
    name: '{{ item }}'
  register: container_info
  loop: '{{ cortex_distributor_ids }}'

- set_fact:
    cortex_distributor_pod_ips: '{{ container_info | json_query(query) }}'
  vars:
    query: 'results[*].containers[0].NetworkSettings.Networks.{{ cortex_backend_podman_network }}.IPAddress'

- name: Setup Cortex Distributors
  containers.podman.podman_container:
    name: 'cortex-distributor-{{ item }}'
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    pod: 'cortex-distributor-{{ item }}-pod'
    conmon_pidfile: '{{ cortex_base_dir }}/pids/cortex-distributor-{{ item }}.pid'
    volume:
      - '{{ cortex_base_dir }}/cortex-config/cortex.yaml:/etc/cortex.yaml:z'
    command: '-target=distributor -config.file=/etc/cortex.yaml'
    state: started
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'
