---
- name: Create Ingesters pods
  containers.podman.podman_pod:
    name: 'cortex-ingester-{{ item }}-pod'
    state: started
    network: '{{ cortex_backend_podman_network }}'
    hostname: 'cortex-ingester-{{ item|string + "." + cortex_domain }}'
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: Get Ingester Infra Containers
  containers.podman.podman_pod_info:
    name: 'cortex-ingester-{{ item|string }}-pod'
  register: pod_info
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- set_fact:
    cortex_ingester_ids: '{{ cortex_ingester_ids|default([]) + [ pod_info.results[ item ].pods[0].State.infraContainerID ] }}'
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: get pod IP
  containers.podman.podman_container_info:
    name: '{{ item }}'
  register: container_info
  loop: '{{ cortex_ingester_ids }}'

- set_fact:
    cortex_ingester_pod_ips: '{{ container_info | json_query(query) }}'
  vars:
    query: 'results[*].containers[0].NetworkSettings.Networks.{{ cortex_backend_podman_network }}.IPAddress'

- name: Setup Cortex Ingesters without WAL
  containers.podman.podman_container:
    name: 'cortex-ingester-{{ item }}'
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    pod: 'cortex-ingester-{{ item }}-pod'
    conmon_pidfile: '{{ cortex_base_dir }}/pids/cortex-ingester-{{ item }}.pid'
    volume:
      - '{{ cortex_base_dir }}/cortex-config/cortex.yaml:/etc/cortex.yaml:z'
    command: '-target=ingester -config.file=/etc/cortex.yaml'
    state: started
  when: cortex_ingesters_with_wal|bool == False
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: Setup Cortex Ingesters with WAL
  containers.podman.podman_container:
    name: 'cortex-ingester-{{ item }}'
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    pod: 'cortex-ingester-{{ item }}-pod'
    conmon_pidfile: '{{ cortex_base_dir }}/pids/cortex-ingester-{{ item }}.pid'
    volume:
      - '{{ cortex_base_dir }}/cortex-config/cortex.yaml:/etc/cortex.yaml:z'
      - 'cortex-ingester-wal-{{ item }}-volume:/wal:Z'
    command: '-target=ingester -config.file=/etc/cortex.yaml'
    state: started
  when: cortex_ingesters_with_wal|bool == True
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- set_fact:
    cortex_ingester_containers: '{{ cortex_ingester_containers|default([]) + [ "cortex-ingester-" +  item|string ] }}'
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: Generate systemd files for ingesters
  include_tasks: systemd.yml
  loop: '{{ cortex_ingester_containers }}'

# Cleanup/scale down
- name: Get list of all ingester pods
  shell: /usr/bin/podman pod ps | grep -o -e 'cortex-ingester-[0-9]\+-pod'
  register: ingester_pods
  changed_when: false

- set_fact:
    pods_in_use: "{{ pods_in_use|default([]) + [ 'cortex-ingester-' + item|string + '-pod' ] }}"
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- set_fact:
    pods_to_cleanup: '{{ ingester_pods.stdout_lines }}'

- set_fact:
    pods_to_cleanup: "{{ pods_to_cleanup | difference(pods_in_use) }}"
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: Get list of all ingester wal volumes
  shell: /usr/bin/podman volume ls | grep -o -e 'cortex-ingester-wal-[0-9]\+-volume'
  register: ingester_volumes
  changed_when: false
  when: cortex_ingesters_with_wal|bool == True

- set_fact:
    volumes_in_use: "{{ volumes_in_use|default([]) + [ 'cortex-ingester-wal-' + item|string + '-volume' ] }}"
  when: cortex_ingesters_with_wal|bool == True
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- set_fact:
    volumes_to_cleanup: '{{ ingester_volumes.stdout_lines }}'
  when: cortex_ingesters_with_wal|bool == True

- set_fact:
    volumes_to_cleanup: "{{ volumes_to_cleanup | difference(volumes_in_use) }}"
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'
  when: cortex_ingesters_with_wal|bool == True

- debug:
    msg: 'Ingester pods to clean up: {{ pods_to_cleanup }}'

- debug:
    msg: 'Ingester volumes to clean up: {{ volumes_to_cleanup }}'

- name: Stop unused Ingesters
  systemd:
    name: "container-{{ item | regex_replace('-pod') }}.service"
    state: stopped
    enabled: no
  loop: '{{ pods_to_cleanup }}'

- name: Cleanup unused Ingester pods
  containers.podman.podman_pod:
    name: '{{ item }}'
    state: absent
  loop: '{{ pods_to_cleanup }}'

- name: Cleanup unused Ingester WAL volumes
  containers.podman.podman_volume:
    name: '{{ item }}'
    state: absent
  loop: '{{ volumes_to_cleanup }}'
  when: cortex_ingesters_with_wal|bool == True

- name: Cleanup unused Ingester service files
  file:
    path: "/etc/systemd/system/container-{{ item | regex_replace('-pod') }}.service"
    state: absent
  loop: '{{ pods_to_cleanup }}'
  notify: daemon-reload
