---
- name: Create Cortex config directory
  file:
    path: /var/lib/containers/cortex-config/
    mode: '0775'
    state: directory

- name: Create Ingester WAL directories
  file:
    path: '/var/lib/containers/cortex-ingester-wal-{{ item }}'
    mode: '0775'
    state: directory
  when: cortex_ingesters_with_wal|bool == True
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'

- name: Set Cortex conf file
  template:
    src: 'cortex.yaml'
    dest: '/var/lib/containers/cortex-config/cortex.yaml'
    mode: '0644'
  register: cortex_conf

- set_fact:
    services_to_restart: '{{ services_to_restart + [ "container-cortex-ingester-" + item|string + ".service" ] }}'
  loop: '{{ range(0, cortex_ingester_replicas)|list }}'
  when: cortex_conf.changed

- set_fact:
    services_to_restart: '{{ services_to_restart + [ "container-cortex-distributor-" + item|string + ".service" ] }}'
  loop: '{{ range(0, cortex_distributor_replicas)|list }}'
  when: cortex_conf.changed
