---
- name: Setup Cortex Table Manager
  containers.podman.podman_container:
    name: 'cortex-table-manager'
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    pod: 'cortex-cassandra-0-pod'
    conmon_pidfile: '{{ cortex_base_dir }}/pids/cortex-table-manager.pid'
    volume:
      - '{{ cortex_base_dir }}/cortex-config/cortex.yaml:/etc/cortex.yaml:z'
    command: '-target=table-manager -cassandra.keyspace={{ cortex_cassandra_keyspace }} -config.file=/etc/cortex.yaml'
    state: started

- name: Generate systemd files for Table Manager
  include_tasks: systemd.yml
  loop:
    - cortex-table-manager
