---
- name: Create Compactor Pod
  containers.podman.podman_pod:
    name: cortex-compactor-pod
    state: started
    network: '{{ cortex_backend_podman_network }}'
    hostname: 'cortex-compactor.{{ cortex_domain }}'

- name: Setup Cortex Compactor
  containers.podman.podman_container:
    name: cortex-compactor
    image: 'quay.io/cortexproject/cortex:{{ cortex_version }}'
    conmon_pidfile: '{{ cortex_base_dir }}/pids/cortex-compactor.pid'
    pod: cortex-compactor-pod
    volume:
      - '{{ cortex_base_dir }}/cortex-config/cortex.yaml:/etc/cortex.yaml:z'
      - cortex-compactor-volume:/compactor
    command: '-target=compactor -config.file=/etc/cortex.yaml'
    state: started

- name: Generate systemd files for Compactor
  include_tasks: systemd.yml
  loop:
    - cortex-compactor

- name: Restart Service
  systemd:
    name: container-cortex-compactor.service
    state: restarted
  when: cortex_conf.changed
