---

- name: Create Cortex config directory
  file:
    path: /var/lib/containers/cortex-config/
    mode: '0775'
    state: directory

- name: Set Cortex conf files
  template:
    src: 'cortex{{ item }}.yml'
    dest: '/var/lib/containers/cortex-config/cortex{{ item }}.yml'
    mode: '0644'
  loop:
    - 0
    - 1
    - 2

- name: Setup Cortex Cluster
  containers.podman.podman_container:
    name: 'cortex-server{{ item }}'
    image: quay.io/cortexproject/cortex:v1.2.0
    pod: 'cortex{{ item }}'
    conmon_pidfile: '/var/lib/containers/pids/cortex{{ item }}.pid'
    volume:
      - '/var/lib/containers/cortex-config/cortex{{ item }}.yml:/etc/cortex.yml:Z'
    command: '-config.file=/etc/cortex.yml'
    state: started
  loop:
    - 0
    - 1
    - 2

- name: Generate systemd files for Cortex cluster
  include_tasks: systemd.yml
  loop:
    - cortex-server0
    - cortex-server1
    - cortex-server2

# Separate role? or variable to use nginx as a LB
- name: Add nginx lb config
  template:
    src: nginx.conf
    dest: /var/lib/containers/cortex-config/nginx.conf
    mode: '0644'

- name: Setup Nginx LoadBalancer
  containers.podman.podman_container:
    name: cortex-loadbalancer
    image: docker.io/library/nginx:latest
    network: prod
    ip: 172.16.20.126
    hostname: cortex.bos2.linuxlab.tech
    conmon_pidfile: '/var/lib/containers/pids/cortex-lb.pid'
    volume:
      - /var/lib/containers/cortex-config/nginx.conf:/etc/nginx/conf.d/default.conf:Z
    state: started

- name: Generate systemd unit content
  shell: podman generate systemd cortex-loadbalancer -n --restart-policy on-failure | tail -n +5
  changed_when: False
  register: systemd

- name: Create unit file
  copy:
    content: '{{systemd.stdout }}'
    dest: /etc/systemd/system/container-cortex-loadbalancer.service
    owner: root
    group: root
    mode: '0644'
  register: unit_file
  notify:
    - daemon-reload
    - Restart cortex-loadbalancer

- name: Start Grafana Server
  systemd:
    name: container-cortex-loadbalancer.service
    state: started
    enabled: yes
  when: unit_file.changed == false
