---
- name: Get infra pods
  containers.podman.podman_pod_info:
    name: '{{ item }}'
  register: pod_info
  loop: '{{ cortex_hostnames_short }}'

- set_fact:
    cortex_pod_ids: '{{ cortex_pod_ids|default([]) + [ pod_info.results[ item ].pods[0].State.infraContainerID ] }}'
  loop: '{{ range(0, cortex_cluster_size)|list }}'

- debug:
    msg: '{{ cortex_pod_ids }}'

- name: get pod IP
  containers.podman.podman_container_info:
    name: '{{ item }}'
  register: container_info
  loop: '{{ cortex_pod_ids }}'

- set_fact:
    cortex_pod_ips: '{{ container_info | json_query(query) }}'
  vars:
    query: 'results[*].containers[0].NetworkSettings.Networks.{{ cortex_podman_network }}.IPAddress'

- debug:
    msg: '{{ cortex_pod_ips }}'
