---
- set_fact:
    services_to_restart: []

- name: Create pid file directory for containers
  file:
    path: '{{ cortex_base_dir }}/pids/'
    state: directory

- include_tasks: etcd.yml
- include_tasks: cassandra.yml
- include_tasks: cortex.yml
- include_tasks: cortex-table-manager.yml
- include_tasks: cortex-distributors.yml
- include_tasks: cortex-ingesters.yml
- include_tasks: cortex-queriers.yml
- include_tasks: nginx.yml

- name: Open nginx port in firewalld
  firewalld:
    port: '{{ cortex_nginx_listen_port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes
  when: cortex_manage_firewalld and cortex_frontend_podman_network == "host"

- debug:
    msg: '{{ services_to_restart }}'

- name: daemon-reload
  systemd:
    daemon-reload: yes
  when: services_to_restart | length > 0

- name: Restart Service(s)
  systemd:
    name: '{{ item }}'
    state: restarted
  loop: '{{ services_to_restart }}'
