---
- set_fact:
    services_to_restart: []

- name: Create pid file directory for containers
  file:
    path: /var/lib/containers/pids/
    state: directory

- include_tasks: etcd.yml
- include_tasks: cassandra.yml
- include_tasks: cortex.yml
- include_tasks: cortex-table-manager.yml
- include_tasks: cortex-distributors.yml
- include_tasks: cortex-ingesters.yml
- include_tasks: cortex-queriers.yml
- include_tasks: nginx.yml

- name: Open nginx port in firewalld
  firewalld:
    port: '{{ cortex_nginx_listen_port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes
  when: cortex_frontend_podman_network == "host"

- debug:
    msg: '{{ services_to_restart }}'
  notify: Restart Service
