---
- name: Add nginx load balancer config
  template:
    src: nginx.conf
    dest: '{{ cortex_base_dir }}/cortex-config/nginx.conf'
    mode: '0644'
  notify: Restart Nginx

- name: Setup Nginx LoadBalancer
  containers.podman.podman_container:
    name: cortex-loadbalancer
    image: docker.io/library/nginx:latest
    conmon_pidfile: '{{ cortex_base_dir }}/pids/cortex-lb.pid'
    volume:
      - '{{ cortex_base_dir }}/cortex-config/nginx.conf:/etc/nginx/nginx.conf:Z'
    state: started

- name: Generate systemd files for nginx
  include_tasks: systemd.yml
  vars:
    item: cortex-loadbalancer
