---
- name: daemon-reload
  systemd:
    daemon-reload: yes

- name: Restart Prometheus
  systemd:
    name: container-prometheus.service
    state: restarted

- name: Restart Grafana-server
  systemd:
    name: container-grafana-server.service
    state: restarted

- name: Restart Grafana-proxy
  systemd:
    name: container-grafana-proxy.service
    state: restarted

- name: Restart AlertManager
  systemd:
    name: container-alertmanager.service
    state: restarted

- name: Restart Blackbox
  systemd:
    name: container-blackbox_exporter.service
    state: restarted

- name: Restart etcd0
  systemd:
    name: container-etcd0.service
    state: restarted
    enabled: yes

- name: Restart etcd1
  systemd:
    name: container-etcd1.service
    state: restarted
    enabled: yes

- name: Restart etcd2
  systemd:
    name: container-etcd2.service
    state: restarted
    enabled: yes

- name: Restart cassandra0
  systemd:
    name: container-cassandra0.service
    state: restarted
    enabled: yes

- name: Restart cassandra1
  systemd:
    name: container-cassandra1.service
    state: restarted
    enabled: yes

- name: Restart cassandra2
  systemd:
    name: container-cassandra2.service
    state: restarted
    enabled: yes

- name: Restart cortex-server0
  systemd:
    name: container-cortex-server0.service
    state: restarted
    enabled: yes

- name: Restart cortex-server1
  systemd:
    name: container-cortex-server1.service
    state: restarted
    enabled: yes

- name: Restart cortex-server2
  systemd:
    name: container-cortex-server2.service
    state: restarted
    enabled: yes

- name: Restart cortex-loadbalancer
  systemd:
    name: container-cortex-loadbalancer.service
    state: restarted
    enabled: yes
